import * as dayjs from 'dayjs';

export interface IFormList {
    etablissement?: string;
    typeDeDemande?: "Installations Techniques" | "Projets Immobiliers" | "";
    date?: dayjs.Dayjs;
    referenceFiche?: string;
    nomDuProjet?: string;
    niveauDePriorite?: 1 | 2 | 3 | "";
    projetDejaPresenteEnN1?: "Oui" | "Non" | undefined;
    anneeDeRealisationDuProjet?: number;
    projetPluriannuel?: "Oui" | "Non" | undefined;
    description?: string;
    miseEnConformite?: "Oui" | "Non" | undefined;
    suitePrescriptionCommissionSecurite?: "Oui" | "Non" | undefined;
    suitePrescriptionBureauControle?: "Oui" | "Non" | undefined;
    suiteVetuste?: "Oui" | "Non" | undefined;
    businessPlanPresente?: "Oui" | "Non" | undefined;
    casDerogatoireBusinessPlanRaison?: string;
    demandeARS?: "Oui" | "Non" | undefined;
    raisonNonImputationCAPEX?: string;
    besoinBET?: "Oui" | "Non" | undefined;
    nomBET?: string;
    besoinBCT?: "Oui" | "Non" | undefined;
    nomBCT?: string;
    besoinCSSI?: "Oui" | "Non" | undefined;
    nomCSSI?: string;
    besoinArchitecte?: "Oui" | "Non" | undefined;
    nomArchitecte?: string;
    besoinCSPS?: "Oui" | "Non" | undefined;
    nomCSPS?: string;
    travauxGenerentEconomiesEnergie?: "Oui" | "Non" | undefined;
    estimationEconomieKWH?: string;
    eligiblesCEE?: "Oui" | "Non" | undefined;
    montantEstimeCEE?: number;
    autresSubventions?: "Oui" | "Non" | undefined;
    montantEstimeSubventions?: number;
    materiauxGroupe?: "Oui" | "Non" | undefined;
    casDerogatoireMateriaux?: string;
    nomFournisseursReference?: string;
    coutTravaux?: number;
    honorairesMissionBET?: number;
    honorairesMissionBCT?: number;
    honorairesMissionCSSI?: number;
    honorairesMissionArchitecte?: number;
    honorairesMissionCSPS?: number;
    honorairesAssurancesTRC_DO?: number;
    autres?: number;
    budgetTotal?: number;
    budgetConsomme2025?: number;
    budgetPrevisionnel2025?: number;
    capexConsomme2026?: number;
    travauxAllotis?: "Oui" | "Non" | undefined;
    nombreDeLots?: number;
    casDerogatoireAllotissement?: string;
    consultation3Entreprises?: "Oui" | "Non" | undefined;
    casDerogatoireConsultation3Entreprises?: string;
    devisNegocies?: "Oui" | "Non" | undefined;
    casDerogatoireDevisNonNegocies?: string;
    nomEntreprise1?: string;
    montantDevis1?: number;
    nomEntreprise2?: string;
    montantDevis2?: number;
    nomEntreprise3?: string;
    montantDevis3?: number;
    nomEntrepriseProposee1?: string;
    montantDevisAvantNegociation1?: number;
    montantApresNegociation1?: number;
    nomEntrepriseProposeeLot1?: string;
    montantDevisAvantNegociationLot1?: number;
    montantApresNegociationLot1?: number;
    nomEntrepriseProposeeLot2?: string;
    montantDevisAvantNegociationLot2?: number;
    montantApresNegociationLot2?: number;
    nomEntrepriseProposeeLot3?: string;
    montantDevisAvantNegociationLot3?: number;
    montantApresNegociationLot3?: number;
    nomLot1?: string;
    nomLot2?: string;
    nomLot3?: string;
    codeEtab?: string;
    modifie?: Date;
    cree?: Date;
    creePar?: string;
    modifiePar?: string;
    StatutFiche?: "Soumise" | "Validée" | "En attente de la DI" | "Refusée" | "En cours" | undefined
    IsCheck?: boolean
}